Services and LogIn/Registration MVVM based on UserDefaults
v1oly/mygarbage1 pull request #19
Opened 2022-01-27 17:53 UTC by v1oly

im not sure that is my userdefaults key objects would work on your pc, just register them in sing up screen.

2022-01-30 03:28 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginModel.swift
> +    case neutral
Мб empty?

2022-01-30 03:29 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginView.swift
> +    var onOpenRegistrationView: () -> ()
onOpenRegistration? Вью тут незачем писать, это детали реализации

2022-01-30 03:30 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewController.swift
> +    func setTuringForStatusCondition(_ statusCondition: LogInStatusCondition) {
Тюринг? Это который машину Тьюринга придумал? Кривое и не говорящее название)

2022-01-30 03:30 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewController.swift
> +        loginView = LoginView(onConfirm: { [weak self] login, password in
каждое замыкание пиши на новой строке

2022-01-30 03:31 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewModel.swift
> +    var accountsListService: AccountsListService = ServiceLocator.shared.getService()
private?

2022-01-30 03:31 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewModel.swift
> +    var onModelUpdate: (LoginModel) -> ()
ну тут везде приваты нужно

2022-01-30 03:32 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewModel.swift
> +    func checkUserLogInToMatchInBase(login: String, password: String) {
Тоже кривое название, слишком сложное и не говорящее при этом

2022-01-30 03:32 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationModel.swift
> +    case neutral
empty?

2022-01-30 03:33 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationView.swift
> +    private let regLoginField = UITextField()
Зачем везде приставка reg? Во-первых это бесполезное сокращение, а во-вторых какой смысл она несет?

2022-01-30 03:33 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationView.swift
> +    init(onRegConfirm: @escaping (String, String, String) -> ()) {
Хорошо бы параметрам замыкания имена давать, а то непонятно что за 3 стринги

2022-01-30 03:33 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationView.swift
> +        super.init(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
Э, убери завязку на скрин. НЕ ПРОПУЩУ ТАКОЕ!

2022-01-30 03:34 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewController.swift
> +            self?.setTuringForStatusCondition(statusCondition: model.currentStatusCondition)
И тут название такое же стремное)

2022-01-30 03:35 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewController.swift
> +                confirmPassword: passwd2
не нужно так даже локальные переменные назвать. Назови говоряще

2022-01-30 03:35 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewModel.swift
> +    var onModelChange: (RegistrationModel) -> ()
Приваты?

2022-01-30 03:36 UTC, west0r commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewModel.swift
> +    func checkIsRegistrationDataHaveMistakesAndSetNewAccountIfHavent(
В стиле того чувака, ага. Целое предложение написал. В целом все понятно, но читать сложно. Как можно сократить?

2022-01-30 03:36 UTC, west0r commented on dz/DZUIKit/Sources/DZUIKit/ArrayListView.swift
> +    public override func sizeThatFits(_ size: CGSize) -> CGSize {
почини линтер тут

2022-01-30 03:36 UTC, west0r commented on dz/DZUIKit/Sources/DZUIKit/ArrayListView.swift
> +        return CGSize(width: min(size.width, 150), height: 210)
так и не сделал тут как надо до конца

2022-01-30 03:38 UTC, west0r commented on dz/dz/Services/AccountsListService.swift
> +        if let userDefaults = userDefaults?.object(forKey: "Accounts") as? [String] {
не есть гуд при ините лезть в дефолтс. Лучше лениво это делать, при первом обращении. Но тут придется юзать синхронизацию потоков по-хорошему)

2022-01-30 03:38 UTC, west0r commented on dz/dz/Services/AccountsListService.swift
> +    private var userAcccountsArray = [String]()
Так и не переделал это)

2022-01-30 03:39 UTC, west0r commented on dz/dz/Services/AccountsListService.swift
> +class AccountsListService {
Сделай этот сервис без костыльного массива, как обсуждали

2022-01-30 03:39 UTC, west0r commented on dz/dz/AppDelegate.swift
> +        print("didIt")
мб удалить этот принт?

2022-01-30 03:40 UTC, west0r requested changes
В целом лучше, чем раньше, но косяки подсветил)

2022-01-30 03:47 UTC, west0r commented on dz/dz/Services/AccountsListService.swift
> +    private let userDefaults = UserDefaults(suiteName: "group.MN.dz")
У меня со стандартным дефолтсом все ок работает

2022-02-13 19:09 UTC, v1oly commented on dz/dz/Services/AccountsListService.swift
> +    private let userDefaults = UserDefaults(suiteName: "group.MN.dz")
поменял на стандартный

2022-02-13 19:10 UTC, v1oly commented on dz/dz/AppDelegate.swift
> +        print("didIt")
удалил

2022-02-13 19:10 UTC, dayomayo42 commented on dz/dz/Services/AccountsListService.swift
> +class AccountsListService {
сделал через дикты

2022-02-13 19:10 UTC, v1oly commented on dz/dz/Services/AccountsListService.swift
> +    private var userAcccountsArray = [String]()
теперь переделал

2022-02-13 19:14 UTC, v1oly commented on dz/dz/Services/AccountsListService.swift
> +        if let userDefaults = userDefaults?.object(forKey: "Accounts") as? [String] {
не совсем врубаю как это делать, покажешь потом

2022-02-13 19:17 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewModel.swift
> +    func checkIsRegistrationDataHaveMistakesAndSetNewAccountIfHavent(
я не знаю вот именно как сократить, либо разбивать на несколько ф-ий (что мне супер не хочется делать) либо придумать другое названия, но я супер хз какое название дать

2022-02-13 19:19 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewModel.swift
> +    var onModelChange: (RegistrationModel) -> ()
сделал

2022-02-13 19:24 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewController.swift
> +                confirmPassword: passwd2
поменял

2022-02-13 19:27 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationViewController.swift
> +            self?.setTuringForStatusCondition(statusCondition: model.currentStatusCondition)
поменял

2022-02-13 19:29 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationView.swift
> +        super.init(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
поправил

2022-02-13 19:31 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationView.swift
> +    init(onRegConfirm: @escaping (String, String, String) -> ()) {
вписал

2022-02-13 19:37 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationView.swift
> +    private let regLoginField = UITextField()
убрал везде рег

2022-02-13 19:39 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/Registration MVVM/RegistrationModel.swift
> +    case neutral
да пофиг нютрал тоже норм по идее

2022-02-13 19:42 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewModel.swift
> +    func checkUserLogInToMatchInBase(login: String, password: String) {
поменял

2022-02-13 19:45 UTC, dayomayo42 commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewController.swift
> +        loginView = LoginView(onConfirm: { [weak self] login, password in
сделал

2022-02-13 19:46 UTC, dayomayo42 commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginViewController.swift
> +    func setTuringForStatusCondition(_ statusCondition: LogInStatusCondition) {
да я еблан где то в переводчике это слово увидел

2022-02-13 19:47 UTC, v1oly commented on dz/dz/Benchmark/LoginRegistrationProject MVVM/LogIn MVVM/LoginView.swift
> +    var onOpenRegistrationView: () -> ()
ну так у меня кнопка с таким же названием, кнопка открывает новый вью контроллер с новой вью, как иначе назвать?

2022-02-15 10:19 UTC, merged